# Geral
key=atualizasom
appName=Atualizasom Rastreamento
siteURL=https://rastreamento.atualizasom.com.br/
allowedHost=rastreamento.atualizasom.com.br

# iOS
iosBundleId=com.atualizasom
iosMarketingVersion=1.0

# Android
androidApplicationId=com.atualizasom
androidVersionCode=25
androidVersionName=${androidVersionCode}.0
